version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "=== Install dependencies with npm ci ==="
      - npm ci || npm install

  build:
    commands:
      - echo "=== Clean & transpile ==="
      - npm run clean || true
      - npm run build || echo "OK"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
