version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  build:
    commands:
      - npm test
artifacts:
  files:
    - "**/*"
reports:
  unit:
    files:
      - "test-results/*.xml"
    file-format: JUNITXML