version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== Install dependencies with npm ci ==="
      - npm ci

  build:
    commands:
      - echo "=== Clean & transpile ==="
      - npm run clean || true
      - npm run build
      - mkdir -p dist-server && echo OK > dist-server/ping.txt
      - echo "=== List expected output folders ==="
      - ls -alR dist-server || true
      - ls -alR public || true
      - ls -alR views || true
      - ls -alR dist || true   

  post_build:
    commands:
      - echo "=== Run tests ==="
      - npm test -- --passWithNoTests
      - echo "=== Prune dev dependencies for deployment ==="
      - npm prune --production
      - echo "=== Build finished ==="

artifacts:
  files:
    - package.json
    - package-lock.json
    - Procfile
    - dist-server/**
    - public/**
    - dist/**
  discard-paths: no
